server:
  port: 9100 # 伺服器的port號

# DB設定
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password:  # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # thymeleaf設定
  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  #MySQL設定
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/MonsterStrike?characterEncoding=utf8&useSSL=false #jdbc:mysql://localhost:3306/MonsterStrike?user=root&password=123456
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver